# Generated by Django 4.1.7 on 2023-04-06 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_jobdescription_jobtitle_applicant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DjangoDB",
        ),
    ]
